dist: trusty
language: node_js
node_js:
  - node
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - export CXX="g++-4.8"
  - npm install -g npm@latest
  - npm install

script:
  - npm test
